version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: pokepump-postgres
    restart: always
    environment:
      POSTGRES_USER: pokepump
      POSTGRES_PASSWORD: pokepump_secret
      POSTGRES_DB: pokepump
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: pokepump-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
